services:
  grafana:
    image: grafana/grafana-oss:11.1.3
    container_name: grafana
    ports:
     - '3000:3000'
    volumes:
      - ./grafana/:/etc/grafana/
      - grafana-storage:/var/lib/grafana
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus:v2.54.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=otlp-write-receiver'
    # ports:
    #   - 9090:9090
    networks:
      - back-tier
      
  loki:
    image: grafana/loki:3.1.1
    # ports:
    #   - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/:/etc/loki/
      - loki-storage:/loki
    networks:
      - back-tier
      
  tempo:
    image: grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-storage:/var/tempo
    # ports:
    #   - "14268:14268"  # jaeger ingest
    #   - "3200:3200"   # tempo
    #   - "9095:9095" # tempo grpc
    #   - "4317:4317"  # otlp grpc
    #   - "4318:4318"  # otlp http
    #   - "9411:9411"   # zipkin
    networks:
      - back-tier

  alloy:
    image: grafana/alloy:1.3.0
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      # - '12345:12345'
      - '4317:4317' # GRPC
      - '4318:4318' # HTTP
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    networks:
      - back-tier

volumes:
  grafana-storage: {}
  prometheus-storage: {}
  loki-storage: {}
  tempo-storage: {}

networks:
  back-tier:
